name: longswipe_flutter_example
description: Example app for the Longswipe Flutter SDK
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  longswipe_flutter:
    path: ../  # Use the local package
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
