name: longswipe
description: A Flutter package for integrating the Longswipe Widget into your application. Provides both a widget-based approach and a controller-based approach for maximum flexibility.
version: 1.0.4
homepage: https://github.com/Telktia-LTD/longswipe-dart-sdk
documentation: https://developer.longswipe.com/docs
topics:
  - voucher
  - protocol
  - crypto-payment
  - remittance-in-crypto
  - exchange-crypto-for-fiat

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.0
  http: ^1.1.0
  external_app_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

